### ISSUE TITLE
SQLite3 over HTTPS is failing, Rails server crashing on MacBook M2 chip. Error: "Missing Symbol Called"

### ISSUE THREAD

**Issue by umairmehar** [sparklemotion/sqlite3-ruby#430] opened 2023-11-27 12:12 UTC
**Issue Summary:**
When attempting to use SQLite3 over HTTPS on a MacBook M2 chip, I'm encountering an error resulting in crashing of the Rails server.

**Error Message:**
Getting this error message without any trace:
`"dyld[XXXXX]: missing symbol called"`

**Reproduction Steps:**
Set up a Rails project on a MacBook M2 chip.
Configure the project to use SQLite3 over HTTPS using thin.
Start the Rails server.
Open any valid URL in the browser.
Observe the error and subsequent crash.

**Expected Behavior:**
The SQLite3 over HTTPS configuration should work seamlessly on MacBook M2 chips without encountering missing symbol errors or causing the Rails server to crash.

**Environment:**
Operating System: macOS (14.1.1 (23B81))
Ruby Version: (3.0.2)
Rails Version: (7.0.8)
SQLite3 Version: (1.6.8-arm64-darwin)
MacBook M2 Chip

**Possible Solutions:**
I can run the application with the same setup and configuration, but using Postgres instead of Sqlite3.

**Comment by flavorjones** [comment] 2023-11-27 21:06
Hi! Thanks for reporting this. I'll try to help.

Can you give me more information about "Configure the project to use SQLite3 over HTTPS using thin"? What are you doing, specifically? I'll need to reproduce what you're seeing in order to diagnose the problem.

**Comment by flavorjones** [comment] 2023-11-27 21:07
In the meantime, a likely workaround would be to avoid using a precompiled native platform gem -- see https://github.com/sparklemotion/sqlite3-ruby/blob/master/INSTALLATION.md#avoiding-the-precompiled-native-gem for help on how to do that.

**Comment by umairmehar** [comment] 2023-11-28 07:36
> Hi! Thanks for reporting this. I'll try to help.
> 
> Can you give me more information about "Configure the project to use SQLite3 over HTTPS using thin"? What are you doing, specifically? I'll need to reproduce what you're seeing in order to diagnose the problem.

Thank you for your response.
I'm generating an SSL certificate for development using the below command:
`openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out tmp/dev-ssl.crt -keyout tmp/dev-ssl.key`

Using this certificate to run the rails server over HTTPS using the below command:
`thin --ssl --ssl-disable-verify --ssl-key-file tmp/dev-ssl.key --ssl-cert-file tmp/dev-ssl.crt --debug start`

[Please also see the attached screenshot for error]
![Error](https://github.com/sparklemotion/sqlite3-ruby/assets/26718949/8a5da8cb-116a-437b-9654-7a82f75156b5)

This setup is working perfectly fine when I use Postgres instead of Sqlite3.

Thank you for suggesting the workaround, I will try using that.

**Comment by umairmehar** [comment] 2023-11-30 08:44
> In the meantime, a possible workaround is: avoid using a precompiled native platform gem -- see https://github.com/sparklemotion/sqlite3-ruby/blob/master/INSTALLATION.md#avoiding-the-precompiled-native-gem for help on how to do that.

This workaround did not work. Getting the same error `dyld[XXXXX]: missing symbol called` and server crashes.

**Comment by flavorjones** [comment] 2023-11-30 13:28
@umairmehar Can you please help me reproduce this? What is in your config.ru, etc.? I'll need to reproduce what you're seeing in order to diagnose the problem.

**Comment by flavorjones** [comment] 2023-11-30 18:01
OK, I've tried and cannot reproduce what you're seeing. Let me tell you what I'm doing, and you need to tell me what's different about your setup.

<details>
<summary>output from `bundle env`</summary>

## Environment

```
Bundler       2.4.22
  Platforms   ruby, arm64-darwin-23
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [arm64-darwin-23]
  Full Path   /Users/flavorjones/.rubies/ruby-3.0.2/bin/ruby
  Config Dir  /Users/flavorjones/.rubies/ruby-3.0.2/etc
RubyGems      3.2.22
  Gem Home    /Users/flavorjones/.gem/ruby/3.0.2
  Gem Path    /Users/flavorjones/.gem/ruby/3.0.2:/Users/flavorjones/.rubies/ruby-3.0.2/lib/ruby/gems/3.0.0
  User Home   /Users/flavorjones
  User Path   /Users/flavorjones/.gem/ruby/3.0.0
  Bin Dir     /Users/flavorjones/.gem/ruby/3.0.2/bin
Tools         
  Git         2.39.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-11-09
Git SHA           ec2089640
Released Version  true
```

## Bundler settings

```
pkgs.shopify.io
  Set for the current user (/Users/flavorjones/.bundle/config): "token:[REDACTED]"
set
  Set for the current user (/Users/flavorjones/.bundle/config): "jobs 2"
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end

gem "thin", "1.8.2"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.1.2)
      actionpack (= 7.1.2)
      activesupport (= 7.1.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    actionmailbox (7.1.2)
      actionpack (= 7.1.2)
      activejob (= 7.1.2)
      activerecord (= 7.1.2)
      activestorage (= 7.1.2)
      activesupport (= 7.1.2)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.1.2)
      actionpack (= 7.1.2)
      actionview (= 7.1.2)
      activejob (= 7.1.2)
      activesupport (= 7.1.2)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.2)
    actionpack (7.1.2)
      actionview (= 7.1.2)
      activesupport (= 7.1.2)
      nokogiri (>= 1.8.5)
      racc
      rack (>= 2.2.4)
      rack-session (>= 1.0.1)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    actiontext (7.1.2)
      actionpack (= 7.1.2)
      activerecord (= 7.1.2)
      activestorage (= 7.1.2)
      activesupport (= 7.1.2)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.1.2)
      activesupport (= 7.1.2)
      builder (~> 3.1)
      erubi (~> 1.11)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    activejob (7.1.2)
      activesupport (= 7.1.2)
      globalid (>= 0.3.6)
    activemodel (7.1.2)
      activesupport (= 7.1.2)
    activerecord (7.1.2)
      activemodel (= 7.1.2)
      activesupport (= 7.1.2)
      timeout (>= 0.4.0)
    activestorage (7.1.2)
      actionpack (= 7.1.2)
      activejob (= 7.1.2)
      activerecord (= 7.1.2)
      activesupport (= 7.1.2)
      marcel (~> 1.0)
    activesupport (7.1.2)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      mutex_m
      tzinfo (~> 2.0)
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    base64 (0.2.0)
    bigdecimal (3.1.4)
    bindex (0.8.1)
    bootsnap (1.17.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    capybara (3.39.2)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    concurrent-ruby (1.2.2)
    connection_pool (2.4.1)
    crass (1.0.6)
    daemons (1.4.1)
    date (3.3.4)
    debug (1.8.0)
      irb (>= 1.5.0)
      reline (>= 0.3.1)
    drb (2.2.0)
      ruby2_keywords
    erubi (1.12.0)
    eventmachine (1.2.7)
    globalid (1.2.1)
      activesupport (>= 6.1)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    importmap-rails (1.2.3)
      actionpack (>= 6.0.0)
      activesupport (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.6.0)
    irb (1.9.1)
      rdoc
      reline (>= 0.3.8)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    matrix (0.4.2)
    mini_mime (1.1.5)
    minitest (5.20.0)
    msgpack (1.7.2)
    mutex_m (0.2.0)
    net-imap (0.4.7)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.4.0)
      net-protocol
    nio4r (2.6.1)
    nokogiri (1.15.5-arm64-darwin)
      racc (~> 1.4)
    psych (5.1.1.1)
      stringio
    public_suffix (5.0.4)
    puma (6.4.0)
      nio4r (~> 2.0)
    racc (1.7.3)
    rack (2.2.8)
    rack-session (1.0.1)
      rack (< 3)
    rack-test (2.1.0)
      rack (>= 1.3)
    rackup (1.0.0)
      rack (< 3)
      webrick
    rails (7.1.2)
      actioncable (= 7.1.2)
      actionmailbox (= 7.1.2)
      actionmailer (= 7.1.2)
      actionpack (= 7.1.2)
      actiontext (= 7.1.2)
      actionview (= 7.1.2)
      activejob (= 7.1.2)
      activemodel (= 7.1.2)
      activerecord (= 7.1.2)
      activestorage (= 7.1.2)
      activesupport (= 7.1.2)
      bundler (>= 1.15.0)
      railties (= 7.1.2)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (7.1.2)
      actionpack (= 7.1.2)
      activesupport (= 7.1.2)
      irb
      rackup (>= 1.0.0)
      rake (>= 12.2)
      thor (~> 1.0, >= 1.2.2)
      zeitwerk (~> 2.6)
    rake (13.1.0)
    rdoc (6.6.0)
      psych (>= 4.0.0)
    redis (5.0.8)
      redis-client (>= 0.17.0)
    redis-client (0.18.0)
      connection_pool
    regexp_parser (2.8.2)
    reline (0.4.1)
      io-console (~> 0.5)
    rexml (3.2.6)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.15.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.6.9-arm64-darwin)
    stimulus-rails (1.3.0)
      railties (>= 6.0.0)
    stringio (3.1.0)
    thin (1.8.2)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (>= 1, < 3)
    thor (1.3.0)
    timeout (0.4.1)
    turbo-rails (1.5.0)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webrick (1.8.1)
    websocket (1.2.10)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.12)

PLATFORMS
  arm64-darwin-23

DEPENDENCIES
  bootsnap
  capybara
  debug
  importmap-rails
  jbuilder
  puma (>= 5.0)
  rails (~> 7.1.2)
  redis (>= 4.0.1)
  selenium-webdriver
  sprockets-rails
  sqlite3 (~> 1.4)
  stimulus-rails
  thin (= 1.8.2)
  turbo-rails
  tzinfo-data
  web-console

BUNDLED WITH
   2.4.22
```
</details>

<details>
<summary>how I setup my rails app</summary>

```
$ rails new foo
...
$ bin/rails generate scaffold post title:string body:text published:boolean
      invoke  active_record
      remove    db/migrate/20231130175226_create_posts.rb
      create    db/migrate/20231130175415_create_posts.rb
   identical    app/models/post.rb
      invoke    test_unit
   identical      test/models/post_test.rb
       force      test/fixtures/posts.yml
      invoke  resource_route
       route    resources :posts
      invoke  scaffold_controller
      create    app/controllers/posts_controller.rb
      invoke    erb
      create      app/views/posts
      create      app/views/posts/index.html.erb
      create      app/views/posts/edit.html.erb
      create      app/views/posts/show.html.erb
      create      app/views/posts/new.html.erb
      create      app/views/posts/_form.html.erb
      create      app/views/posts/_post.html.erb
      invoke    resource_route
      invoke    test_unit
      create      test/controllers/posts_controller_test.rb
      create      test/system/posts_test.rb
      invoke    helper
      create      app/helpers/posts_helper.rb
      invoke      test_unit
      invoke    jbuilder
      create      app/views/posts/index.json.jbuilder
      create      app/views/posts/show.json.jbuilder
      create      app/views/posts/_post.json.jbuilder

$ bin/rails db:migrate
== 20231130175415 CreatePosts: migrating ======================================
-- create_table(:posts)
   -> 0.0031s
== 20231130175415 CreatePosts: migrated (0.0032s) =============================
```
</details>

<details>
<summary>output from running the server</summary>

```
$ bundle exec thin --ssl --ssl-disable-verify --ssl-key-file dev-ssl.key --ssl-cert-file dev-ssl.crt --debug start
2023-11-30 13:01:05 -0500 Using rack adapter
2023-11-30 13:01:06 -0500 Thin web server (v1.8.2 codename Ruby Razor)
2023-11-30 13:01:06 -0500 Debugging ON
2023-11-30 13:01:06 -0500 Maximum connections set to 1024
2023-11-30 13:01:06 -0500 Listening on 0.0.0.0:3000, CTRL+C to stop
8146902720:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1556:SSL alert number 46
8146902720:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1556:SSL alert number 46
8146902720:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1556:SSL alert number 46
8146902720:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1556:SSL alert number 46
8146902720:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1556:SSL alert number 46
8146902720:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1556:SSL alert number 46
8146902720:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1556:SSL alert number 46
8146902720:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1556:SSL alert number 46
```
</details>

And the app responds fine. I'm able to read/write sqlite3 database records fine.

**Comment by flavorjones** [comment] 2023-12-12 23:51
Closing. If you can provide steps for me to reproduce this, please do comment and I'm happy to investigate.

**Closed by flavorjones** 2023-12-12 23:51 UTC
