### ISSUE TITLE
Cannot load such file -- sqlite3/sqlite3_native (LoadError)

### ISSUE THREAD

**Issue by Learning191** [sparklemotion/sqlite3-ruby#240] opened 2018-09-02 06:12 UTC
At this time I just updated the ruby ​​to the ruby ​​version `2.5.1p57 (revision 2018-03-29 63029) [i386-mingw32]` update it with `rubyinstaller-devkit-2.5.1-2-x86. exe` , when I try to execute `rails s` shows me this error  :

    $ rails s
    C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
    1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- 
    sqlite3/sqlite3_native (LoadError)
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:287:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13-x86-mingw32/lib/sqlite3.rb:6:in `rescue in 
     <top (required)>'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13-x86-mingw32/lib/sqlite3.rb:2:in `<top 
     (required)>'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in 
     require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
      1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:81:in `block (2 
      levels) in require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `each'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `block in 
     require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `each'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler.rb:114:in `require'
         from C:/users/angulo/projects_ruby/projects_rails/rails_app/config/application.rb:18:in `<top 
     (required)>'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in 
     require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:287:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties- 
     5.2.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties- 
     5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties- 
     5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in ` 
     invoke_command'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top 
     (required)>'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap 
    -1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
          from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in 
    require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
    1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
    1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
    1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
    5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
    5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
    5.2.1/lib/active_support/dependencies.rb:287:in `require'
        from bin/rails:4:in `<main>'

Clearly does not let me ` require 'sqlite3' `

I try to solve it with issues like : [https://github.com/sparklemotion/sqlite3-ruby/issues/185](url) ,
[https://github.com/sparklemotion/sqlite3-ruby/issues/185](url) , but none of the solutions that this poetry worked for me

My environment : 
- Windows 7 x32 bits
- ruby ​​version `2.5.1p57 (revision 2018-03-29 63029) [i386-mingw32]
- Rails 5.2.1

To reproduce :
- run ` rails new rails_app `
- run ` rails s `

I hope it is solved, Thanks for reading

**Comment by PujaSrivastava10** [comment] 2018-09-07 17:40
@Learning191 , I am still facing the same issue. Were you able to resolve it ?

**Comment by PujaSrivastava10** [comment] 2018-09-07 17:49
@Learning191 , you can use : https://github.com/sparklemotion/sqlite3-ruby/issues/224#issuecomment-416800097, 

I tried resolving by the above method and got the server working for ruby 2.5 and rails 5.2.1.
There seems to be a sqllite3 issue.

**Comment by Learning191** [comment] 2018-09-08 10:27
@PujaSrivastava10 [https://github.com/sparklemotion/sqlite3-ruby/issues/224#issuecomment-416800097](url) not worked for me

**Comment by Learning191** [comment] 2018-09-08 10:29
@sharifzadesina equally the error happens to me in that console

**Comment by sharifzadesina** [comment] 2018-09-08 10:30
@Learning191 So what should we do? I didn't find any solution. it seems the problem is how they link to library.

**Comment by Learning191** [comment] 2018-09-08 10:49
@sharifzadesina that seems to be, I've been searching and searching but I can not find any solution

**Comment by KnappeGEIL** [comment] 2018-09-10 10:47
+1, have the same issue. Can't find a solution for this problem.

**Comment by gabrielwillemann** [comment] 2018-09-10 16:47
+1

**Comment by Kostronor** [comment] 2018-09-12 19:15
Same thing happening with win10 and 64bit. Tried compiling myself, tried downgrading sqlite or bundler, nothing works

**Comment by aliaga5037** [comment] 2018-09-17 15:21
+1

**Comment by xamvac73** [comment] 2018-09-20 23:50
I am also getting the same error...using windows 8 64bit...
Rails 5.1.6
ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]

is there anyone who could help? appreciate it in advance.

**Comment by alaurie** [comment] 2018-10-24 03:41
This still fixes it for me.

gem uninstall sqlite3 --all
ridk exec pacman -S mingw-w64-x86_64-sqlite3
gem inst sqlite3 --platform ruby

**Comment by whatisc** [comment] 2018-10-28 01:29
The above works for me.

**Comment by dipto0321** [comment] 2018-10-29 04:02
The above solution works for me. thanks @alaurie

**Comment by dipto0321** [comment] 2018-10-31 12:13
> This still fixes it for me.
> 
> ```
> gem uninstall sqlite3 --all
> ridk exec pacman -S mingw-w64-x86_64-sqlite3
> gem inst sqlite3 --platform ruby
> ```

I need to run the above solution every time when I generate rails new app. Is there any way to fix that problem permanently?

**Comment by bwl21** [comment] 2018-11-09 12:07
I tried to do these steps but it failed:
```
checking for sqlite3.h... no
sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
```


I do not know, what excactly I should install from https://www.sqlite.org/download.html. Any hint is highly appreciated.

However it is, I wonder why there is no binary stuff for sqlite with ruby 2.4, 2.5 out there ;-(

**Comment by ulropka** [comment] 2018-11-28 22:36
i spent a lot of time before coming across this fix.....     did the trick for me.

**Comment by katalin13** [comment] 2018-11-29 20:14
:'(  nothing works for me . . .
I am very new, I tried a lot, but still can't make it work...

I do the new rails project, go into the project and for rails s it gives me the same error message.

C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)

Either is really not helping, or I am doing it wrong...

I am using Windows 10 64
ruby  2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
Rails 5.2.1.1

**Comment by DJLProjects** [comment] 2018-12-11 19:39
@alaurie you're my absolute savior. Been working at this for weeks. Your solution is the only one to work. Thank you.

**Comment by JLBeals** [comment] 2018-12-18 16:11
Thank you @alaurie for this. Hours of searching for a fix and this finally did it!

**Comment by zueskei** [comment] 2019-01-09 08:37
than

> This still fixes it for me.
> 
> ```
> gem uninstall sqlite3 --all
> ridk exec pacman -S mingw-w64-x86_64-sqlite3
> gem inst sqlite3 --platform ruby
> ```

Thank you so muchhhhhhhhh

**Comment by permanar** [comment] 2019-01-10 07:17
> This still fixes it for me.
> 
> ```
> gem uninstall sqlite3 --all
> ridk exec pacman -S mingw-w64-x86_64-sqlite3
> gem inst sqlite3 --platform ruby
> ```

This worked.

**Comment by alon1samuel** [comment] 2019-01-23 14:00
> This still fixes it for me.
> 
> ```
> gem uninstall sqlite3 --all
> ridk exec pacman -S mingw-w64-x86_64-sqlite3
> gem inst sqlite3 --platform ruby
> ```

Thanks, @alaurie  👍  for me it fixed the problem of running the command
`rails server`

Regards, Alon

**Comment by ricardoruizfp** [comment] 2019-01-29 11:44
> This still fixes it for me.
> 
> ```
> gem uninstall sqlite3 --all
> ridk exec pacman -S mingw-w64-x86_64-sqlite3
> gem inst sqlite3 --platform ruby
> ```

I had the same issue today. alaurie, you're a legend. Thanks!

**Comment by bwl21** [comment] 2019-01-29 11:56
I agree, but it still does not work for me ... 
```
checking for sqlite3.h... no
sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
```

I have installed SQLite 3 several times, without success ...



```
c:> gem inst sqlite3 --platform ruby


W:\100_VirtualRevolution-svn\30_WorkShop\SRC_Optigem_bridge\99_experiments>gem inst sqlite3 --platform ruby
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13/ext/sqlite3
C:/Ruby25/bin/ruby.exe -r ./siteconf20190129-3468-11doi7x.rb extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-config
        --without-sqlite3-config
        --with-pkg-config
        --without-pkg-config
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby25/lib/ruby/gems/2.5.0/extensions/x86-mingw32/2.5.0/sqlite3-1.3.13/mkmf.log

extconf failed, exit code 1
```

**Comment by alaurie** [comment] 2019-01-29 12:35
@bwl21 you need to install the sqlite3 headers with the below.

ridk exec pacman -S mingw-w64-x86_64-sqlite3

**Comment by bwl21** [comment] 2019-01-30 09:05
@alaurie sorry, absolutely no success:

```
C:\WortsammlerBib.1.8.1>ridk exec pacman -S mingw-w64-x86_64-sqlite3
Warnung: mingw-w64-x86_64-sqlite3-3.15.0-1 ist aktuell -- Reinstalliere
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...

Pakete (1) mingw-w64-x86_64-sqlite3-3.15.0-1

Gesamtgröße der installierten Pakete:  4,56 MiB
Größendifferenz der Aktualisierung:  0,00 MiB

:: Installation fortsetzen? [J/n] J
(1/1) Prüfe Schlüssel im Schlüsselring                                                                                                        [#####################################################################################] 100%
(1/1) Überprüfe Paket-Integrität                                                                                                              [#####################################################################################] 100%
(1/1) Lade Paket-Dateien                                                                                                                      [#####################################################################################] 100%
(1/1) Prüfe auf Dateikonflikte                                                                                                                [#####################################################################################] 100%
(1/1) Überprüfe verfügbaren Festplattenspeicher                                                                                               [#####################################################################################] 100%
:: Verarbeite Paketänderungen...
(1/1) Installiere mingw-w64-x86_64-sqlite3                                                                                                    [#####################################################################################] 100%

C:\WortsammlerBib.1.8.1>gem inst sqlite3 --platform ruby
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13/ext/sqlite3
C:/Ruby25/bin/ruby.exe -r ./siteconf20190130-1612-1p58hii.rb extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-config
        --without-sqlite3-config
        --with-pkg-config
        --without-pkg-config
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby25/lib/ruby/gems/2.5.0/extensions/x86-mingw32/2.5.0/sqlite3-1.3.13/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby25/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13 for inspection.
Results logged to C:/Ruby25/lib/ruby/gems/2.5.0/extensions/x86-mingw32/2.5.0/sqlite3-1.3.13/gem_make.out
```

this is the ... mkmf.log


```
"pkg-config --exists sqlite3"
package configuration for sqlite3 is not found
find_header: checking for sqlite3.h... -------------------- no

"i686-w64-mingw32-gcc -o conftest.exe -IC:/Ruby25/include/ruby-2.5.0/i386-mingw32 -IC:/Ruby25/include/ruby-2.5.0/ruby/backward -IC:/Ruby25/include/ruby-2.5.0 -I. -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -march=i686 -mtune=generic -O2 -pipe conftest.c  -L. -LC:/Ruby25/lib -L. -pipe -s     -lmsvcrt-ruby250  -lgmp -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

"i686-w64-mingw32-gcc -E -IC:/Ruby25/include/ruby-2.5.0/i386-mingw32 -IC:/Ruby25/include/ruby-2.5.0/ruby/backward -IC:/Ruby25/include/ruby-2.5.0 -I. -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -march=i686 -mtune=generic -O2 -pipe  conftest.c -o conftest.i"
conftest.c:5:21: fatal error: sqlite3.h: No such file or directory
 #include <sqlite3.h>
                     ^
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <sqlite3.h>
/* end */

--------------------

```

**Comment by bwl21** [comment] 2019-01-30 15:27
I enventually deinstalled ruby 2.5, and started from scratch. Now it is working :-) according to your solution. Thanks.

**Comment by mallikarjunece** [comment] 2019-02-12 13:24
> +1, have the same issue. Can't find a solution for this problem.

+1

**Comment by MSP-Greg** [comment] 2019-02-18 17:14
Re installing on Windows with Ruby >= 2.4, used the following with both Ruby trunk & 2.5.3:

```
ridk exec pacman -S mingw-w64-x86_64-sqlite3
ridk exec pacman -S mingw-w64-x86_64-dlfcn
gem install sqlite3
```

**Comment by MSP-Greg** [comment] 2019-02-18 18:20
If anyone wants to try a pre-compiled Windows gem for Ruby versions 2.0 thru 2.6, download:
64 bit:
https://ci.appveyor.com/api/buildjobs/70mpx8d7usanliff/artifacts/sqlite3-1.3.13.20180326210955-x64-mingw32.gem

32 bit:
https://ci.appveyor.com/api/buildjobs/ynvehayawybc2iwx/artifacts/sqlite3-1.3.13.20180326210955-x86-mingw32.gem

install using `gem install -l <path to gem file>`

The gems do not require any external dll files in MSYS or MSYS2.

**Comment by Reckordp** [comment] 2019-02-23 06:55
@MSP-Greg I have followed your instructions and replaced x86_64 with i686, and this works thanks.
```
D:\Program>gem install -l sqlite3-1.4.0.gem --platform=ruby -- --with-sqlite3-in
clude=D:/Windows/Software/SQlite/Conf --with-sqlite3-lib=D:/Windows/Software/SQl
ite/Conf/.libs
Temporarily enhancing PATH for MSYS/MINGW...
Installing required msys2 packages: mingw-w64-i686-sqlite3
Could Not Find D:\Software\Windows\Ruby25\msys32\usr\bin\msys-2.0.dll.dat
The directory name is invalid.
Could Not Find D:\Software\Windows\Ruby25\msys32\usr\bin\msys-gcc_s-1.dll.dat
The directory name is invalid.
The directory name is invalid.
Could Not Find D:\Software\Windows\Ruby25\msys32\usr\bin\msys-2.0.dll.dat
warning: mingw-w64-i686-sqlite3-3.27.1-1 is up to date -- skipping
Building native extensions with: '--with-sqlite3-include=D:/Windows/Software/SQl
ite/Conf --with-sqlite3-lib=D:/Windows/Software/SQlite/Conf/.libs'
This could take a while...
Successfully installed sqlite3-1.4.0
Parsing documentation for sqlite3-1.4.0
Installing ri documentation for sqlite3-1.4.0
Done installing documentation for sqlite3 after 3 seconds
1 gem installed
```

**Comment by bwl21** [comment] 2019-05-27 13:03
There is also a solution desrcibed in https://medium.com/@declancronje/installing-and-troubleshooting-ruby-on-rails-sqlite3-windows-10-fix-87c8886d03b

The solution there installs the sqlite3 gem from github

**Comment by alaurie** [comment] 2019-05-27 22:24
From checking yesterday. The SQLite3 gem now installs the relevant SQlite3 files into RIDK first and then builds and installs the gem correctly on Windows now.

**Comment by sukeerthiadiga** [comment] 2019-07-09 06:55
To remain still on 1.3

```gem "sqlite3", git: "https://github.com/sparklemotion/sqlite3-ruby.git", ref: "b6862d8"```

**Closed** 2019-07-23 19:26 UTC

**Comment by Learning191** [comment] 2019-07-23 19:28
Hallelujaaaaah, This work for me guys

[https://github.com/sparklemotion/sqlite3-ruby/issues/240#issuecomment-432501696](url)

![2019-07-23 15_16_56-Ruby on Rails](https://user-images.githubusercontent.com/26369137/61741263-79974a80-ad5e-11e9-9628-0334fa08df97.png)

**Comment by GeneciCruz** [comment] 2020-11-09 23:07
This still fixes it for me.

gem uninstall sqlite3 --all
ridk exec pacman -S mingw-w64-x86_64-sqlite3
gem inst sqlite3 --platform ruby

Thank you so much!

**Comment by Nisticism** [comment] 2020-12-13 09:25
I'm having the same problem to this day, and the above solution didn't work for me.  

I'm getting a whole host of errors:

:: Retrieving packages...
error: failed retrieving file 'mingw-w64-x86_64-pdcurses-4.1.0-1-any.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-pdcurses-4.1.0-1-any.pkg.tar.xz' from sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-pdcurses-4.1.0-1-any.pkg.tar.xz' from www2.futureware.at : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-pdcurses-4.1.0-1-any.pkg.tar.xz' from mirror.yandex.ru : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-readline-8.0.000-3-any.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-readline-8.0.000-3-any.pkg.tar.xz' from sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-readline-8.0.000-3-any.pkg.tar.xz' from www2.futureware.at : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-readline-8.0.000-3-any.pkg.tar.xz' from mirror.yandex.ru : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'mingw-w64-x86_64-sqlite3-3.28.0-2-any.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-sqlite3-3.28.0-2-any.pkg.tar.xz' from sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-sqlite3-3.28.0-2-any.pkg.tar.xz' from www2.futureware.at : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-sqlite3-3.28.0-2-any.pkg.tar.xz' from mirror.yandex.ru : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

Any idea how to fix?

**Comment by sg552** [comment] 2021-01-04 01:49
> Any idea how to fix? I get this when running the second command (ridk exec pacman -S mingw-w64-x86_64-sqlite3)

seems your network is not good. try another mirror near your location. google for how to change the pacman mirror

**Comment by ShehanAT** [comment] 2021-04-23 17:30
> I enventually deinstalled ruby 2.5, and started from scratch. Now it is working :-) according to your solution. Thanks.

Hey, did you install a Ruby version before or after 2.5?

**Comment by bwl21** [comment] 2021-04-23 17:32
I have reinstalled ruby 2.5.

**Comment by GBaldez** [comment] 2021-12-22 00:50
I can't run this command `ridk exec pacman -S mingw-w64-x86_64-sqlite3` 
Says ridk: command not found

**Comment by wtfiwtz** [comment] 2021-12-29 04:01
@GBaldez are you using Windows and do you have Ruby with the DevKit installed?
https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.0.3-1/rubyinstaller-devkit-3.0.3-1-x64.exe

If you are on Mac / Linux I don't think this is a requirement. If you are, perhaps you need something like this:

**Mac**
```
brew install sqlite3
gem install sqlite3 -- --with-sqlite3-include=/usr/local/Cellar/sqlite/3.37.0/include \
   --with-sqlite3-lib=/usr/local/Cellar/sqlite/3.37.0/lib
```

**Ubuntu / Debian Linux**
```
sudo apt-get install libsqlite3-dev
gem install sqlite3 -- --with-sqlite3-include=/usr/include \
   --with-sqlite3-lib=/usr/lib/x86_64-linux-gnu
```
