### ISSUE TITLE
Reproducible segmentation fault in resultset.rb

### ISSUE THREAD

**Issue by forthrin** [sparklemotion/sqlite3-ruby#384] opened 2023-03-23 08:28 UTC
The crash, which happens during a `select`, may be memory related (too large data?) as it disappears when imposing a `limit`.

Let me know if you have a fix or if you need further testing.

[ruby.txt](https://github.com/sparklemotion/sqlite3-ruby/files/11048517/ruby.txt)
[sqlite3.txt](https://github.com/sparklemotion/sqlite3-ruby/files/11048518/sqlite3.txt)

**Comment by flavorjones** [comment] 2023-03-26 19:08
@forthrin Sorry you're experiencing a segfault. Thank you for reporting this.

Can you help us reproduce this?

**Comment by forthrin** [comment] 2023-03-26 20:06
Sure. The loop in this contrived example code gets a segmentation fault after around 2k iterations.

```
  db = SQLite3::Database.open('/tmp/tmp.sqlite')
  db.execute('create table if not exists foo (id int)')
  db.execute('delete from foo')
  100.times do
    db.execute('insert into foo values (random())')
  end
  tables = []
  loop do
    tables << db.execute('select * from foo')
  end
```

**Comment by flavorjones** [comment] 2023-03-27 13:49
@forthrin This example keeps all responses forever in the `tables` array, which is essentially a memory leak and the process eventually triggers an OOM condition. I'm not sure there's anything we can do to prevent a failure of some kind, though I admit the software should probably fail more gracefully. Am I understanding what you're seeing correctly?

**Comment by forthrin** [comment] 2023-03-27 14:02
The example code was just meant to quickly trigger the issue. The real code triggers the issue with only two iterations of the response with 100k rows x 1 integer coloumn. Why does this constitutes OOM on a machine with 8 GB RAM and disk swapping? Who triggers the OOM? Your library, the Ruby core or macOS?

**Comment by flavorjones** [comment] 2023-03-27 16:58
> The example code was just meant to quickly trigger the issue

For whatever it's worth, it's hard to reproduce what you're seeing on my machine. I have 16GB and it takes far longer than 2000x iterations with the example script to reach a memory limit and OOM.

> Who triggers the OOM

This is likely the `malloc` system call returning a `NULL` because the process can no longer allocate memory.

If you can demonstrate this occurring in a case where this isn't the issue, I'd be happy to look into it. If you have more questions, I'll try to answer, but in the meantime I don't think there's anything we can do from within this gem to avoid this situation, so I'm going to close this.

**Closed by flavorjones** 2023-03-27 16:58 UTC

**Comment by flavorjones** [comment] 2023-03-27 17:06
You can see a similar effect without this gem if you run:

```
str = "asdf" * 100

tables = []
loop do
  tables << str.dup
end
```

Eventually the process will be killed when it hits the OOM point.

**Comment by forthrin** [comment] 2023-03-27 19:23
I just don't understand how 100 x 2000 rows x 1 integer (around 1,5 MB raw data) can create an OOM on a 8 GB machine, unless the result set object has a humongous overhead.

And does OOM even happen on modern computers? Doesn't swapping to disk kick in automatically from an OS level?

Again, do you know if the OOM fails occurs from a call in your code, the Ruby core or on an OS level? And shouldn't there be some fail-safe handling of this eventuality prior to just letting things wind up in a segfault?

I'll be happy to run more specific tests to clarify the issue.

PS! While writing this message, your code ran some 30+ million iterations without creating an OOM on my machine.
