### ISSUE TITLE
Having trouble with CTE using v3.1.12

### ISSUE THREAD

**Issue by donvnielsen** [sparklemotion/sqlite3-ruby#198] opened 2016-10-27 21:43 UTC
Using sqlite3 gem `v3.1.12`
Using sqlite3 `v3.15.0 2016-10-14 10:20:30 707875582fcba352b4906a595ad89198d84711d8`

What is the highest version of Sqlite supported by the gem?  I'm having trouble with the following sql statement. It throws an exception on the 'WITH': 
`SQLite3::SQLException: near "with": syntax error:`

I can submit the statement using the command line sqlite3 and it functions correctly. I had changed my ruby code do exactly that via %x. However, the open connection does not detect the change in the sql database, so the resulting table fulfilled_needs table is not visible in the code.

Thank you very much for your time and consideration, dvn

**Ruby implementation**

``` ruby
      %x(sqlite3 #{DB_NAME} "#{sql.join(' ')}")
```

**Full SQL statement**

``` SQL
create table fulfilled_needs as with
tbl_0 as (
SELECT nms.mail_need_id as mail_need_id, nms.id as needs_matching_supply_id
FROM needs_matching_supplies nms
JOIN mail_needs need ON need.id = nms.mail_need_id
WHERE need.lvl = '0-reg' AND need.need_qty = 1
ORDER BY lvl, need.avg_prty, nms.avg_pool_prty, nms.seq
LIMIT 5
)
, tbl_1 as (
SELECT nms.mail_need_id as mail_need_id, nms.id as needs_matching_supply_id
FROM needs_matching_supplies nms
JOIN mail_needs need ON need.id = nms.mail_need_id
WHERE need.lvl = '0-reg' AND need.need_qty = 2
ORDER BY lvl, need.avg_prty, nms.avg_pool_prty, nms.seq
LIMIT 10
)
, tbl_2 as (
SELECT nms.mail_need_id as mail_need_id, nms.id as needs_matching_supply_id
FROM needs_matching_supplies nms
JOIN mail_needs need ON need.id = nms.mail_need_id
WHERE need.lvl = '1-hd' AND need.need_qty = 1
ORDER BY lvl, need.avg_prty, nms.avg_pool_prty, nms.seq
LIMIT 0
)
SELECT mail_need_id, needs_matching_supply_id FROM tbl_0
union all SELECT mail_need_id, needs_matching_supply_id FROM tbl_1
union all SELECT mail_need_id, needs_matching_supply_id FROM tbl_2
;
```

**Comment by tenderlove** [comment] 2016-11-17 22:58
Hi,

I'm pretty confused.  Would it be possible to create a sample script that reproduces the problem in Ruby?  Everything you do on the commandline should also be possible in the SQLite3 gem.

**Comment by donvnielsen** [comment] 2016-11-18 14:47
Give me the weekend to prepare a Sqlite db for you, and stripped down script that reproduces the problem. How can I send the db to you?

**Comment by donvnielsen** [comment] 2016-11-19 02:58
The attached zip contains three files: aan.db, it.rb, and cte_with.sql. 

it.rb has the trace output from running the sql within rubymine and running it from the command line. The sql runs fine within the sqlite3 shell. 

[sparklemotion_pkg.zip](https://github.com/sparklemotion/sqlite3-ruby/files/601214/sparklemotion_pkg.zip)

**Comment by donvnielsen** [comment] 2016-12-09 13:28
I'm just following up on this. Did you happen to take a look at this problem and determine if I am doing something incorrectly or if there is an issue? Thanks, dvn

**Comment by donvnielsen** [comment] 2016-12-09 20:34
One more update. There must be something in the code that is being brought down and compiled into sqlite_native.so. It is all I can think of. Your C code in the ext/ and lib/ folders is identical between the two environments. I've eliminated the possibility of line_endings (LF vs CRLF) tripping up sqlite3 db. The only variable left that I can identify is the amalgamation code that is brought down. I've gone deeper than what my knowledge is capable of.

**Comment by donvnielsen** [comment] 2016-12-10 14:48
Using sqlite3 gem v3.1.12
Using sqlite3 v3.15.0 2016-10-14 10:20:30 707875582fcba352b4906a595ad89198d84711d8

I now understand what is happening. The sqlite3 gem compiles its own instance of sqlite, using version 3.8.11.1 (2105), as specified in the file, native.rake. The sql language I am using is not compatible with that version. Can you tell me how to trigger the compilation process using the existing unpacked gem code? I made the following change to native.rake and would like to give it a shot:

``` ruby
# BINARY_VERSION = "3.8.11.1"
# URL_VERSION    = "3081101"
# URL_PATH       = "/2015"
BINARY_VERSION = "3.15.2.0"
URL_VERSION    = "3150200"
URL_PATH       = "/2016"
```

**Comment by tenderlove** [comment] 2017-01-31 22:41
@donvnielsen when you install the gem you can specify what to compile and link against by using `--with-sqlite3-{dir,include,lib}` flags.  For example `gem install sqlite3 -- --with-sqlite3-dir=blah`, or you can use the other options to manually specify lib or include dirs.

I'm going to close this because it doesn't sound like a bug in the gem itself.  You might also want to ping the sqlite3-ruby mailing list.  My knowledge about compiling and linking for Windows is pretty limited, and there might be people on the list who can better help.

**Closed by tenderlove** 2017-01-31 22:41 UTC
